#!/bin/bash
#
#	* File     : online_wallpaper
#	* Author   : sunowsir
#	* Mail     : sunowsir@163.com
#	* Github   : github.com/sunowsir
#	* Creation : 2025年07月31日 星期四 00时48分25秒

LOCK_FILE='/var/run/online_wallpaper_run.lock'
WORK_SH_FILE='/usr/libexec/argon/online_wallpaper_proc'

flock "${LOCK_FILE}" "${WORK_SH_FILE}" "${@}"
