#!/bin/bash
# author jjm2473
# modify author sun.wang fork to https://github.com/sunowsir/luci-theme-argon

WEB_PIC_SRC=$(uci -q get argon.@global[0].online_wallpaper || echo 'bing')
API_KEY=$(uci -q get argon.@global[0].use_api_key)
CURL_MAXTIME=$(uci -q get argon.@global[0].get_timeout || echo '30')
RESOLUTION_X=$(uci -q get argon.@global[0].reso_x || echo '2560')
RESOLUTION_Y=$(uci -q get argon.@global[0].reso_y || echo '1440')

# 图片存储路径, web js 代码会从该路径获取bg
BACKGROUND_IMG_PATH='/www/luci-static/argon/img/'

CACHE=/var/run/argon_${WEB_PIC_SRC}.url
RUNNING_CACHE=${BACKGROUND_IMG_PATH}/argon_bg.url

WRLOCK=/var/lock/argon_${WEB_PIC_SRC}.lock

# 默认一小时刷新一次
REFRESH_INTERVAL_SEC=$((1 * 60 * 60))

function fetch_pic_url_pexels() {
    if [[ -z "${API_KEY}" ]]; then
        return 
    fi

    local result
    result=$(curl -s --max-time "${CURL_MAXTIME}" -H "Authorization: ${API_KEY}" \
        "https://api.pexels.com/v1/curated?per_page=80&page=1")


    if [[ "${result}" == "" ]]; then
        return 
    fi

    local per_page
    per_page=$(echo "${result}" | jsonfilter -qe '@["per_page"]')

    for ((idx = 0; idx < per_page; idx++));
    do
        local random_idx=$((RANDOM % RANDOM % per_page))

        local node_filter
        node_filter='@["photos"]['${random_idx}']'

        local width 
        width=$(echo "${result}" | jsonfilter -qe "${node_filter}"'.width')
        if [[ ${width} -lt ${RESOLUTION_X} ]]; then
            continue
        fi

        local height
        height=$(echo "${result}" | jsonfilter -qe "${node_filter}"'.height')
        if [[ ${height} -lt ${RESOLUTION_Y} ]]; then
            continue
        fi

        if [[ ${width} -lt ${height} ]]; then
            continue
        fi

        echo "${result}" | jsonfilter -qe "${node_filter}"'.src.original'

        break;
    done

    return 
}

function fetch_pic_url() {

    case ${WEB_PIC_SRC} in
    bing)
        declare picpath
        picpath=$(curl -fks --max-time "${CURL_MAXTIME}" \
            "https://www.bing.com/HPImageArchive.aspx?format=js&n=1&uhd=1" |
            jsonfilter -qe '@.images[0].url')
        [[ -n "${picpath}" ]] && echo "//www.bing.com${picpath}" | sed "s/w=[0-9]*/${RESOLUTION_X}/g" | sed "s/h=[0-9]*/${RESOLUTION_Y}/g"
        ;;
    unsplash)
        # fix from https://github.com/sbwml/luci-theme-argon
        if [[ -z "${API_KEY}" ]]; then
            curl -fks --max-time "${CURL_MAXTIME}" \
                --header "Authorization: Client-ID kmFIroj2ELqXJPtC0XUoyww-Tr_lDU8Ho8uxjptIrCo" \
                "https://api.unsplash.com/photos/random?count=1&orientation=landscape" |
                jsonfilter -e "@[0]['urls']['regular']"
        else
            curl -fks --max-time "${CURL_MAXTIME}" \
                "https://api.unsplash.com/photos/random?client_id=${API_KEY}" |
                jsonfilter -qe '@["urls"]["regular"]'
        fi
        ;;
    unsplash_*)
        local collection_id=${WEB_PIC_SRC#unsplash_}
        if [[ -z "${API_KEY}" ]]; then
            curl -fks --max-time "${CURL_MAXTIME}" \
                "https://source.unsplash.com/collection/${collection_id}/${RESOLUTION_X}x${RESOLUTION_Y}" |
                sed -E 's#^.*href="([^?]+)\?.*$#\1?fm=jpg\&fit=crop\&w='"${RESOLUTION_X}"'\&h='"${RESOLUTION_Y}"'#'
        else
            curl -fks --max-time "${CURL_MAXTIME}" \
                "https://api.unsplash.com/photos/random?client_id=${API_KEY}&collections=${collection_id}" |
                jsonfilter -qe '@["urls"]["regular"]'
        fi
        ;;
    pexels)
        fetch_pic_url_pexels
        ;;
    picsum)
        echo 'https://picsum.photos/2560/1440'
        ;;
    esac
}

function try_update() {
    local lock="${WRLOCK}"
    exec 200>"${lock}"

    rm -rf "${CACHE}"

    if flock -n 200 >/dev/null 2>&1; then
        declare picurl
        picurl=$(fetch_pic_url)
        if [[ "${WEB_PIC_SRC}" == wallhave* ]] ; then
            curl -fks --max-time "${CURL_MAXTIME}" --url "${picurl}" > /dev/null
        fi
        if [[ -n "${picurl}" ]]; then
            echo "${picurl}" | tee "${CACHE}"
        else
            if [[ -s "$CACHE" ]]; then
                cat "${CACHE}"
            else
                touch "${CACHE}"
            fi
        fi

        flock -u 200 >/dev/null 2>&1

    elif [[ -s "${CACHE}" ]]; then
        cat "${CACHE}"
    fi
}

function get_url() {
    if [[ -f "${CACHE}" ]] && [[ -s "${CACHE}" ]] && 
       [[ -f "${RUNNING_CACHE}" ]] && [[ -s "${RUNNING_CACHE}" ]]; then
        local idle_t=$(($(date '+%s') - $(date -r "${CACHE}" '+%s' 2>/dev/null || echo '0')))
        if [[ ${idle_t} -le ${REFRESH_INTERVAL_SEC} ]] && [[ $(cat "${CACHE}" | tr -d '\n') == $(cat "${RUNNING_CACHE}") ]]; then
            return
        fi
    fi
    try_update
}

function main() {
    declare img_url
    img_url="$(get_url)"

    if [[ "${img_url}" != "" ]]; then
        rm -rf ${BACKGROUND_IMG_PATH}/bg.jpg

        curl --http1.1 -L -fks --max-time "${CURL_MAXTIME}" \
            -A "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36" \
            --url "$(echo "${img_url}" | sed 's/^\/\///g')" -o ${BACKGROUND_IMG_PATH}/bg.jpg

        echo "${img_url}" > "${RUNNING_CACHE}"
    fi

    cat "${CACHE}"
}

main "${@}"
exit $?

