#!/bin/bash
#
#	* File     : online_wallpaper
#	* Author   : sunowsir
#	* Mail     : sunowsir@163.com
#	* Github   : github.com/sunowsir
#	* Creation : 2025年07月31日 星期四 00时48分25秒

G_LOCK_FILE='/var/run/online_wallpaper.lock'
G_WORK_SH_FILE='/usr/libexec/argon/online_wallpaper_proc'
G_WORK_LOGS='/var/log/online_wallpaper.log'

flock "${G_LOCK_FILE}" /bin/bash -x "${G_WORK_SH_FILE}" "${@}" > ${G_WORK_LOGS} 2>&1 
